spring:
  application:
    name: policy-service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.code.policy: DEBUG
    org.springframework.web: INFO
