services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama-ci
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL:-qwen2.5-coder:7b}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        /bin/ollama serve &
        sleep 5
        /bin/ollama pull $${OLLAMA_MODEL}
        wait

volumes:
  ollama-data:
    driver: local
