spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen2.5-coder:3b
        options:
          temperature: 0.3
    vertex:
      ai:
        gemini:
          project-id: test-project
          location: us-central1
          chat:
            model: gemini-2.0-flash-001
            options:
              temperature: 0.3

ai:
  provider: ollama
  client:
    ollama:
      response-timeout: 10m
      connect-timeout: 15s
      max-tokens: 7680
    gemini:
      max-tokens: 100000
  prompts:
    ollama:
      code-review-prompt: classpath:prompts/ollama/code-review.md
      review-merge-prompt: classpath:prompts/ollama/review-merge.md
    gemini:
      code-review-prompt: classpath:prompts/gemini/code-review.md
      review-merge-prompt: classpath:prompts/gemini/review-merge.md

github:
  base-url: http://localhost:8080
  token: test-token
  review-path: /repos/{owner}/{repo}/pulls/{pull_number}/reviews
  client:
    response-timeout: 300s
    connect-timeout: 5s

cli:
  repository:
    owner: test-owner
    name: test-repo
  pr-number: 123
  time-out-minutes: 1
